#!/bin/bash

if [ -z "${HOST_IP}" ]; then
    EC2_ENDPOINT=http://169.254.169.254/latest/meta-data/local-ipv4
    if curl -s --connect-timeout 1 $EC2_ENDPOINT > /dev/null; then
        HOST=$(curl -s $EC2_ENDPOINT)
        export HOST_IP=$HOST
    fi
fi
